functions_csv = "data/odyssey_functions.csv"
build_target = "odyssey"

[decomp_me]
compiler_name = "clang-3.9.1"
default_compile_flags = "-x c++ -O3 -g2 -std=c++1z -fno-rtti -fno-exceptions -Wall -Wextra -fno-strict-aliasing"
