name: Trigger full-sync on the tracker repo on push

on:
  push:
    branches:
      - master

jobs:
  api-trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the api to start workflow 
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.HEADERS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/MonsterDruide1/OdysseyDecompTracker/actions/workflows/155550252/dispatches \
          -d '{"ref":"master"}'
